services:
  postgres:
    image: postgres:15-alpine
    container_name: casafacil_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: casafacil_db
      POSTGRES_USER: casafacil_user
      POSTGRES_PASSWORD: casafacil_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - casafacil_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U casafacil_user -d casafacil_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Opcional: PgAdmin para administração visual do banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: casafacil_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@casafacil.com.br
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - casafacil_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  casafacil_network:
    driver: bridge 